import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowRight, BadgeCheck, Bolt, Building2, Car, CheckCircle2, Clock, Factory, Home, Lightbulb, MapPin, Menu, Phone, ShieldCheck, Sparkles, Star, Wrench, X, Zap } from 'lucide-react';
import { areas, business, nav, pages, reviews, services } from './data.js';

const pageIcons = { Emergency: Zap, Switchboards: ShieldCheck, 'Fault Finding': Wrench, Residential: Home, Commercial: Building2, Industrial: Factory, Lighting: Lightbulb, 'EV Charging': Car, Power: Bolt };
const pageFilter = { emergency: ['Emergency', 'Fault Finding'], residential: ['Residential', 'Lighting', 'Power', 'EV Charging', 'Switchboards'], commercial: ['Commercial', 'Lighting', 'Switchboards', 'Fault Finding'], industrial: ['Industrial', 'Switchboards', 'Fault Finding'], switchboards: ['Switchboards', 'Fault Finding'], services: null };

function setPage(page) { window.history.pushState({}, '', `#${page}`); window.dispatchEvent(new HashChangeEvent('hashchange')); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function usePage() { const [page, update] = useState(() => window.location.hash.replace('#', '') || 'home'); useEffect(() => { const f = () => update(window.location.hash.replace('#', '') || 'home'); window.addEventListener('hashchange', f); return () => window.removeEventListener('hashchange', f); }, []); return page; }

function Logo() { return <button className="logo" onClick={() => setPage('home')}><span><Bolt size={23} /></span><b>Imperial</b><small>Electric Services</small></button>; }
function Header({ page }) { const [open, setOpen] = useState(false); return <header className="header"><div className="utility"><span><Star size={14} /> {business.rating} • {business.reviews}</span><span><Clock size={14} /> {business.hours}</span><span><MapPin size={14} /> {business.address}</span></div><div className="nav"><Logo /><nav className={open ? 'links open' : 'links'}>{nav.map(([id, label]) => <button className={page === id ? 'active' : ''} key={id} onClick={() => { setPage(id); setOpen(false); }}>{label}</button>)}</nav><div className="actions"><a href={`tel:${business.tel}`} className="call"><Phone size={17} /> {business.phone}</a><button onClick={() => setPage('contact')} className="primary">Request quote</button></div><button className="menu" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div></header>; }

function Hero() { return <section className="hero"><div className="heroTexture" /><div className="container heroGrid"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.7}}><p className="eyebrow"><span /> 24/7 certified electrician • Green Valley NSW</p><h1>Electrical work that feels precise, clean and genuinely professional.</h1><p className="lead">Imperial Electric Services delivers expert electrical solutions with a focus on safety, precision and reliability across residential, commercial and industrial projects in Green Valley, South West Sydney and nearby areas.</p><div className="heroButtons"><a className="primary big" href={`tel:${business.tel}`}>Call {business.phone}</a><button className="secondary big" onClick={() => setPage('contact')}>Request a quote <ArrowRight size={18} /></button></div><div className="trust">{['5.0 Google rating', '28 Google reviews', 'Open 24 hours', 'Residential • Commercial • Industrial'].map(x => <span key={x}><CheckCircle2 size={16} />{x}</span>)}</div></motion.div><motion.aside className="heroCard" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{duration:.7,delay:.1}}><div className="cardHeader"><span>Live service profile</span><strong>24/7</strong></div><div className="panelOrb"><Zap size={58} /></div><div className="serviceMini">{['Emergency repairs', 'Switchboard upgrades', 'Fault finding', 'EV chargers'].map(x => <div key={x}><BadgeCheck size={18} />{x}</div>)}</div><div className="locationCard"><MapPin size={20} /><div><b>{business.address}</b><small>{business.serviceArea}</small></div></div></motion.aside></div></section>; }

function SectionHead({kicker,title,copy,button}) { return <div className="sectionHead"><div><p className="kicker">{kicker}</p><h2>{title}</h2>{copy && <p className="copy">{copy}</p>}</div>{button}</div>; }
function ServiceCards({ filter }) { const list = useMemo(() => !filter ? services : services.filter(s => filter.includes(s.group)), [filter]); return <section className="section"><div className="container"><SectionHead kicker="Services" title="Electrical services built for trust and response." copy="A premium service layout that makes the business look established, organised and easy to contact." button={<button className="secondary" onClick={() => setPage('contact')}>Start a quote</button>} /><div className="serviceGrid">{list.map((s, i) => { const Icon = pageIcons[s.group] || Bolt; return <motion.article className="serviceCard" key={s.title} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.04}}><div className="icon"><Icon size={24} /></div><p>{s.group}</p><h3>{s.title}</h3><span>{s.copy}</span><a onClick={() => setPage('contact')}>Enquire now <ArrowRight size={15} /></a></motion.article>; })}</div></div></section>; }
function Emergency() { return <section className="emergency"><div className="container emergencyGrid"><div><p className="kicker">Emergency electrical</p><h2>Unsafe power should be handled before it becomes serious.</h2><p>If you notice burning smells, sparks, repeated tripping, power loss or unsafe outlets, stop using the affected circuit and contact a certified electrician.</p><div className="warningTags">{['Power outages','Burning smells','Tripping circuits','Faulty outlets','Switchboard faults','Urgent repairs'].map(t => <span key={t}><Zap size={15}/>{t}</span>)}</div></div><div className="callBox"><small>Open 24 hours</small><a href={`tel:${business.tel}`}>{business.phone}</a><button className="primary" onClick={() => setPage('emergency')}>Emergency page</button></div></div></section>; }
function Why() { const values = [['Safety first','Compliant, careful work that protects the property.'],['Fair pricing','Positioned around honest pricing and clear communication.'],['Quality finish','Clean workmanship customers can feel confident about.'],['Fast response','24/7 emergency availability for urgent issues.']]; return <section className="section cream"><div className="container split"><div><p className="kicker">Why Imperial</p><h2>Premium enough for big jobs. Local enough to feel personal.</h2><p className="copy">This design makes Imperial look like a serious, high-value electrical company without feeling fake or over-designed.</p></div><div className="values">{values.map(([a,b]) => <div key={a}><ShieldCheck size={24}/><h3>{a}</h3><p>{b}</p></div>)}</div></div></section>; }
function Reviews() { return <section className="section reviews"><div className="container"><SectionHead kicker="Reviews" title="5.0 rated by local customers." copy="Real review snippets only, presented cleanly and professionally." /><div className="reviewGrid">{reviews.map(r => <article key={r.name}><div>★★★★★</div><p>“{r.quote}”</p><b>{r.name}</b></article>)}</div></div></section>; }
function Areas() { return <section className="section"><div className="container"><SectionHead kicker="Service areas" title="Green Valley, Liverpool and South West Sydney." copy="Built around local search intent for nearby suburbs and the broader Sydney area." /><div className="areas">{areas.map(a => <span key={a}>{a}</span>)}</div></div></section>; }
function Process() { return <section className="section dark"><div className="container"><SectionHead kicker="Process" title="A clear process that feels professional from the first call." copy="The customer knows what happens before, during and after the job." /><div className="process">{[['01','Call or request quote'],['02','Assess and diagnose'],['03','Complete clean work'],['04','Test and explain']].map(([n,t]) => <div key={n}><b>{n}</b><h3>{t}</h3><p>Simple, organised and focused on safety, reliability and clear communication.</p></div>)}</div></div></section>; }
function Contact() { return <section className="section contact"><div className="container contactGrid"><form onSubmit={e=>e.preventDefault()}><p className="kicker">Quote request</p><h2>Request electrical work.</h2><div className="two"><input placeholder="Name"/><input placeholder="Phone"/></div><div className="two"><input placeholder="Email"/><input placeholder="Suburb"/></div><div className="two"><select><option>Service needed</option><option>Emergency electrical</option><option>Switchboard upgrade</option><option>Fault finding</option><option>Lighting</option><option>EV charger</option></select><select><option>Urgency</option><option>Today</option><option>This week</option><option>Planning ahead</option></select></div><textarea placeholder="Tell us what is happening or what you need installed."/><button className="primary big">Request my electrical quote</button></form><aside><h3>Call Imperial Electric Services</h3><a className="phone" href={`tel:${business.tel}`}>{business.phone}</a><p>{business.hours}</p><div><MapPin /> {business.address}</div><div><Star /> {business.rating} from {business.reviews}</div><div className="map"><span>Map location</span><b>Green Valley NSW 2168</b></div></aside></div></section>; }
function HomePage(){ return <><Hero/><ServiceCards/><Emergency/><Why/><Process/><Reviews/><Areas/><FinalCta/></>; }
function Inner({page}){ if(page==='contact') return <><InnerHero page={page}/><Contact/></>; const filter = pageFilter[page]; return <><InnerHero page={page}/><ServiceCards filter={filter}/>{page==='emergency'&&<Emergency/>}<Why/><Reviews/><FinalCta/></>; }
function InnerHero({page}){ const [title,copy] = pages[page] || pages.services; return <section className="innerHero"><div className="container"><p className="kicker">Imperial Electric Services</p><h1>{title}</h1><p>{copy}</p><div className="heroButtons"><a className="primary" href={`tel:${business.tel}`}>Call {business.phone}</a><button className="secondary" onClick={()=>setPage('contact')}>Request quote</button></div></div></section>; }
function FinalCta(){ return <section className="final"><div className="container finalBox"><div><p className="kicker">Ready to contact</p><h2>Get a certified electrician on the job.</h2><p>24/7 emergency support, residential, commercial and industrial electrical services across Green Valley and nearby Sydney areas.</p></div><a className="primary big" href={`tel:${business.tel}`}>Call {business.phone}</a></div></section>; }
function Footer(){ return <footer><div className="container footerGrid"><div><Logo/><p>Imperial Electric Services delivers expert electrical solutions with a focus on safety, precision and reliability.</p></div><div>{nav.slice(1).map(([id,label])=><button key={id} onClick={()=>setPage(id)}>{label}</button>)}</div><div><b>Contact</b><a href={`tel:${business.tel}`}>{business.phone}</a><span>{business.address}</span><span>{business.hours}</span><span>@{business.instagram}</span></div></div></footer>; }
export default function App(){ const page=usePage(); return <><Header page={page}/>{page==='home'?<HomePage/>:<Inner page={page}/>}<Footer/><div className="mobileBar"><a href={`tel:${business.tel}`}><Phone size={17}/>Call</a><button onClick={()=>setPage('contact')}>Quote</button></div></>; }
